version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu

before_build:
  pwsh: dotnet restore Itn.SnkUtils.sln
after_build:
  pwsh: dotnet pack --include-symbols -c Release Itn.SnkUtils.sln
build:
  verbosity: minimal
  publish_core_console: true
artifacts:
  - path: '**\*.nupkg'
    name: "NuGetPackages_$(APPVEYOR_BUILD_IMAGE)"
# deploy:
#   - provider: NuGet
#     api_key:
#       secure: [add apikey for nuget]
#     on:
#       APPVEYOR_REPO_TAG: true
#     artifact: NuGetPackages
#   - provider: GitHub
#     auth_token:
#       secure: [add auth_token for github release]
#     artifact: NuGetPackages
#     draft: false
#     prerelease: false
#     on:
#       branch: master
#       appveyor_repo_tag: true
