version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu

before_build:
  pwsh: dotnet restore Itn.SnkUtils.sln
after_build:
  pwsh: dotnet pack --include-symbols -c Release Itn.SnkUtils.sln
build:
  verbosity: minimal
  publish_core_console: true
artifacts:
  - path: '**\*.nupkg'
    name: "NuGetPackages_$(APPVEYOR_BUILD_WORKER_IMAGE)"
deploy:
  - provider: NuGet
    api_key:
      secure: ObdX/i2R/d8X/M7w59smkL5LxkufRAuSY8X92XLBhMFrTcw2ZH4wloHQVYEq8zHE
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    artifact: "NuGetPackages_$(APPVEYOR_BUILD_WORKER_IMAGE)"
  - provider: GitHub
    auth_token:
      secure: aHs6VkoaNK4A64BzdJTMiKcOZ89BD0rVixpILmDy1pAU4749uwysMZXBV+4lzrYl
    artifact: "NuGetPackages_$(APPVEYOR_BUILD_WORKER_IMAGE)"
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
